# Make file for Userlogin program

# Building the executable
.PHONY : build
build:
	g++ main.cpp UserReg.cpp -I/home/hariprasaath/codes/headers -o Userapp


# Runnning the program
.PHONY : run
run:
	./Userapp

# Cleaning th files
.PHONY : clean

clean:
	rm -f Userapp
